### ISSUE TITLE
Cobaltstrike CNA issue

### ISSUE THREAD

**Issue by bspence7337** [Mr-Un1k0d3r/PowerLessShell#1]
Awesome stuff. I love the Cobaltstrike integration. I ran into a problem however when laterally moving to a host I have local admin on. The randomly generated project file does get uploaded, but the MSBuild.exe command execution doesn't seem to occur. The wmi cmd.exe call doesn't appear to execute.

-I used the following syntax:
beacon> wmi_build target ListenerName

**Things I validated**:
-wmi_msbuild.cna is in cobalstrike directory
-PowerLessShell git clone is in subdirectory of cobaltstrike directory
-When I execute the "MSBUILD.exe XxXxx.TMP" manually on the target the it runs like a champ. Just not with the cobaltstrike beacon alias integration with the .cna provided.

<img width="857" alt="powerlessshell-cna-issue" src="https://user-images.githubusercontent.com/13281324/27152919-214ab198-5115-11e7-92a3-04ee6a55f817.png">

Please advise
-bSpence7337

**Comment by Mr-Un1k0d3r** [comment]
Hi I've reached out to MrT__F he is currently investigation the issue. As soon as I get the fix I'll update the ticket and the code.

Thanks,

**Comment by Mr-Un1k0d3r** [comment]
Can you post the script_console output, The script contains several println() debug statement in there that prints the wmic cmd line call. You could try manually executing that with shell <command line> and see what WMI output is returned. It also can be a permission issue.

**Comment by bspence7337** [comment]
Apologies, looks like this was a permission issue. I ran this out of a different sandbox (less locked down) and it worked like a champ.
